### ISSUE TITLE
reset.cssを導入すべきだろうか

### ISSUE THREAD

**Issue by rendaman0215** [rendaman/clester#6]
h2 等のタグはブラウザによってデフォルトの挙動が異なる。
ブラウザバリエーションにより、デザインが崩壊する可能性があるため、
それらの挙動を一度殺すcss が reset.css

ただしreset.cssを導入すると、既存の画面は崩壊しそう。。。

**Comment by kamina-zzz** [comment]
ブラウザが勝手にスタイルあててくるのはうざいよねー

**Comment by kamina-zzz** [comment]
言いそびれたけどこのあたりがおすすめです( 使うのであれば、だけど )

http://html5doctor.com/html-5-reset-stylesheet/
